version: '3.8'
services:
  app:
    build: .                                    # image: ghcr.io/pren-dfgjsv/pren_recognition:latest # OR local -> build: .
    container_name: 'recognition-app'
    environment:
      DEPLOY_ENV: prod                          # prod -> run webserver | dev -> execute recognition directly
      PYTHONUNBUFFERED: 1                       # show log output
    # network_mode: host
    ports:
      - 5000:5000                               # or expose: - 5000