name: CI/CD (GitHub Container Registry)
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: PREN_Recognition

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and deploy to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and deploy
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ env.REPOSITORY }}
        tags: latest
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
